### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by oestradiol** [dapplion/rs-car#11]
Hello! Thanks for making this project. It's been really useful, especially to deal with the CAR files used in the [ATProtocol Repositories](https://atproto.com/specs/repository). I really appreciate it.

Now, I wanted to ask something. I noticed that this crate was put under either APACHE 2.0 or MIT Licenses on [crates.io](https://docs.rs/crate/rs-car/latest/source/Cargo.toml), but noticed the licensing files are not included here on this repo.

On my project, I'm working with a different version of the [IPLD crate (ipld-core) that relies on `serde` more](https://github.com/ipld/rust-ipld-core/), rather than the version used here, [`libipld`](https://github.com/ipld/libipld). Because of that, I wanted to rewrite an alternative version of this code using `ipld-core` instead, so that it would fit my needs better. I was initially planning on uploading it to crates.io as a separate crate, but I might as well make a Pull Request if you prefer.

I wanted to know if that would be OK, and if you choose the former rather than the latter, I kindly request you to include the LICENSE file here so that I am allowed to do it.

Thanks,
\- Elaina

**Comment by oestradiol** [comment]
Hello @dapplion. Sorry to bother. Any updates on this?

I'm not sure if the crate is still being maintained, but if not, please let me know. Thanks!

**Comment by dapplion** [comment]
Hey @oestradiol thanks for the ping. I'll be happy to review a PR of yours. Will add the license file, thanks for noting that.

**Comment by ascpixi** [comment]
This probably can be closed now that #12 has been merged.
